apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidly-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vidly
  template:
    metadata:
      labels:
        app: vidly
        tier: backend
    spec:
      containers:
        - name: vidly-backend
          image: mrehanabbasi/vidly-backend-ci-cd
          resources:
            limits:
              memory: "1Gi"
              cpu: "800m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: vidly
    tier: backend
  ports:
    - port: 3900
      targetPort: 3000
