apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vidly-app
spec:
  selector:
    app: vidly
    tier: db
    role: mongo
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: vidly-app
spec:
  selector:
    matchLabels:
      role: mongo
  serviceName: db
  replicas: 2
  template:
    metadata:
      labels:
        app: vidly
        tier: db
        role: mongo
        replicaSet: MainRepSet
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:4.2.12-bionic
          command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "MainRepSet"
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage-claim
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage-claim
        annotations:
          volume.beta.kubernetes.io/storage-class: "standard"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
