apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidly-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vidly-frontend
  template:
    metadata:
      labels:
        app: vidly
        tier: frontend
    spec:
      containers:
        - name: vidly-frontend
          image: mrehanabbasi/vidly-frontend-ci-cd
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: vidly
    tier: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 4000
