apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidly-frontend
  namespace: vidly-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vidly
  template:
    metadata:
      labels:
        app: vidly
        tier: frontend
    spec:
      containers:
        - name: vidly-frontend
          image: mrehanabbasi/vidly-frontend-ci-cd:latest
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            failureThreshold: 2
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 30
            failureThreshold: 2
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: vidly-app
spec:
  type: NodePort
  selector:
    app: vidly
    tier: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
